apiVersion: v1
kind: Service
metadata:
  name: {{ include "flappy-bird.fullname" . }}
  labels:
    {{- include "flappy-bird.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "flappy-bird.name" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
