replicaCount: 2

image:
  repository: ziyadtarek99/flappy-bird-game
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources: {}

ingress:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
